# Configuracion de seguridad
encryptPassword=true
storePasswordAsHex=true
initialPasswordForAdmin=admin

# Opciones de navegacion
startInLastVisitedModule=true
showModulesMenuWhenNotLogged=true

# Esquemas de base de datos (PostgreSQL)
createSchema=CREATE SCHEMA ${schema}
createSchema.PostgreSQL=CREATE SCHEMA ${schema}
createSchema.HSQL=CREATE SCHEMA ${schema} AUTHORIZATION DBA
dropSchema=DROP SCHEMA ${schema} CASCADE
dropSchema.MySQL=DROP SCHEMA ${schema}

# Otras opciones
showApplicationName=true
showOrganizationOnSignIn=false
showListOfOrganizationsOnSignIn=false
updateNaviOXTablesInOrganizationsOnStartup=true
